### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by funkyfuture**
@03b8, before i might end up in a chat about what i've done so far, this one has more images.

the docs are still missing though.

### CODE REVIEW

**Comment by 03b8** [comment]
if i understand correctly, this implements #3, right? so using this feature i could for instance rewrite `snakesist.NodeResource` as an extension of `delb.Document`?

**Comment by funkyfuture** [comment]
yes. of course i still need to write the related docs that give useful hints. here's what i have on my mind now:

- the mixin classes are extensions, meaning that they cannot override attributes b/c the `Document` class' methods do no `super` calls
  - if you think that the class needs hooks, eg. for pre- or post-init, i can add these where needed
- the attributes provided by an extension should share a common prefix, eg `exist_`

my idea for `snakesist` (and other storage plugins) was so far:

- the plugin defines a struct that points to the backend and optionally to a known resource
  - for `snakesist` that would be an `ExistClient` instance as well as the document and the node id
- the plugin registers a document loader that handles these structs
- the extensions class implements methods for updating, deleting and creating resources

but i just realized that there's yet no way for a loader to return/store properties like the document / node id that the extension needs to know. i'll probably reflect on the on my upcoming walk. atm, i'd say the `Document.__init__` would be extended to take arbitrary keyword-arguments and pass them to aforementioned hooks. another way would to extend the result of a loader with a dictionary that is used to set properties of a new instance.

what would you say is preferable?

```python
an_exist_client = snakesist.ExistClient(…)
resource = snakesist.DocumentResource("foo", an_exist_client)
document = delb.Document(resource)
```

or 

```python
an_exist_client = snakesist.ExistClient(…)
document = delb.Document("foo", exist_client=an_exist_client)
```

what i'm struggling conceptionally with atm is that i like to keep the loader order as flexible as now, while adding hooks that can also interfere with document loading is redundant and is less flexible, but dictated by a class' mro.

and also, how could a `Document` instance be used to access, let's say eXist-db and postgres at the (figuratevly) same time?

**Comment by 03b8** [comment]
i have to admit i feel a bit overwhelmed by the issue, as i'm still grappling with the plugin, extension and hook concepts.

regarding the two examples: intuitively i would prefer the less verbose one, but i'm not sure what its drawbacks would be.

on your last question: this might be a dumb assumption, but i was thinking that using multiple databases could look like this:
```python
an_exist_client = snakesist.ExistClient(…)
document = delb.Document("foo", db_client=an_exist_client)
```
```python
a_postgres_client = some_xml_postgres_module.PostgresClient(…)
document = delb.Document("foo", db_client=a_postgres_client)
```

**Comment by funkyfuture** [comment]
> i have to admit i feel a bit overwhelmed by the issue, as i'm still grappling with the plugin, extension and hook concepts.

so was i, i got some things sorted out (and my question what would be preferable turned out to be misleading, but still helpful):

- responsibility for loading stays with the loaders, extension classes must not be able to override the loading
  - but loaders need to be able to return properties that will be set on the instance (resp. its `_config` property, see next)
- all keywords on a `Document` initialization are stored in a `_config` property, to be used by extension classes
- i'll probably add a post-init-hook for extensions from the start, further hook additions on the `Document` class must be justified by compelling reasons

this means one can configure and multiple database backends on the same document instance:

```python
# that's speculating how a Postgres plugin would work
a_postgres_client = PostgresClient(
    [connection_params],
    query_factory=my_apps_query_factory_for_postgres
)

doc = delb.Document(
    exist_resource,
    exist_client=an_exist_client,
    postgres_client=a_postgres_client
)
doc.postgres_save(identifier=something_will_be_consumed_by_the_query_factory)
```

btw, i looked at the xml functionalities of Postgres and they aren't really useful. but a char field is good enough as container.

and, i will see whether i can port the Redis-caching TEI/DTABf model i used for my app to an extension class. but that's a time-consuming task.

i hope i can finish this one here to a usable/testable state within a week.

**Comment by funkyfuture** [comment]
okay, i updated the pr. shall i make a development release to make the docs available on rtd? and for you to have a distribution to work with?

**Comment by funkyfuture** [comment]
it's now available for testing:

- https://pypi.org/project/delb/0.2.dev0/
- https://delb.readthedocs.io/en/0.2dev0/
  - https://delb.readthedocs.io/en/0.2dev0/extending.html

**Comment by 03b8** [comment]
That's awesome! I will try to take a look and play around with the new stuff during the upcoming weekend and hope to be able to give you some feedback afterwards.

**Comment by 03b8** [comment]
After going through parts of the pluggy docs I'm slowly beginning to understand what the whole deal with plugins is and I'm starting to like it :)

I played around a bit with the Document extension and noticed that the `clone()` method for extended Document classes throws a `KeyError` after causing a second call to `_init_config()` with a meanwhile empty `config` parameter. The traceback will look something like this:
```python
    some_document_extension_object.clone()
  File "delb/__init__.py", line 263, in clone
    result = self.__class__(self.root, parser=self.config.parser)
  File "delb/__init__.py", line 190, in __init__
    self._init_config(config)  # type: ignore
  File "some_delb_plugin.py", line 10, in _init_config
    some_property=config.pop("some_property")
KeyError: 'some_property'
```
The extension class being declared like this:
```python
class SomeDocumentExtension:
    def _init_config(self, config):
        self.config.some = SimpleNamespace(
            some_property=config.pop("some_property")
        )
```

Not sure though if I did something wrong while configuring the plugin here or if it might be a bug...

**Comment by funkyfuture** [comment]
> I'm slowly beginning to understand what the whole deal with plugins is

if you have something that would make a better introduction to the topic, let me know. things are always too common to myself once i grasped them.

> noticed that the clone() method

that is was anticipating as probable bug, but wanted to wait for actual uses. i'll appoint you as collaborator on the repo, so you could push a unit test to this pr.

regarding the actual problem: there was a problem with `deepcopy` ing the config object. i'm not sure whether it should be copied at all or just get attached to the document clone. but in your case metadata like the document and node ids would have to be mutable, right?

**Comment by 03b8** [comment]
for me the [main page of the pluggy docs](https://pluggy.readthedocs.io/en/latest/#how-does-it-work) with its examples was a really good, gradual introduction to the topic. so i think for prospective `delb` plugin developers the existing link to the pluggy docs should be enough.

thanks for inviting me as a collaborator; i'll add that unit test sometime during this weekend.

and yes, if i'm not mistaken, `snakesist` in its current implementation assumes the mutability of those properties.

**Comment by funkyfuture** [comment]
i changed the behaviour in order to create a deep copy of the config object. it's available as `0.2dev1`.

concerning the bug: it was rather one in the test case, b/c that extension class assumed that a specific configuration value would be passed. that wouldn't make sense when a config is copied. the capability to enforce configuration data is gone now, but well, be it so.

**Comment by funkyfuture** [comment]
i'm closing this in favor of a new PR

**Pull request closed without merging**
